name: Go-panikint self-compile and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Build Go-Panikint compiler
      run: |
        cd src
        ./make.bash

    - name: Run tests
      run: |
        cd tests
        GOROOT=${{ github.workspace }} ${{ github.workspace }}/bin/go test -v .
